#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <cstdlib>
#include <crtdbg.h>
#include <iostream>
#include <cmath>
#include <cstring>
#include <string>
#include <vector>
#include <fstream>
#include <windows.h>
#include <new>
#include <exception>
#include <list>
#include <algorithm>
#include <iterator>
#include <deque>
#include <set>
#include <map>
#include <iomanip>